lint.vlt
test/cache_tb.sv
design/data_array.sv
design/memory.sv
design/tag_array.sv
design/writeback_buffer.sv
design/memory_controller.sv
design/cache_controller.sv
design/top.sv
design/directory.sv
design/relocation.sv
--Wall 
--trace-vcd
--Wno-fatal
--timing
